version: '0.1.0.{build}'
image: Visual Studio 2019
install: git submodule update --init --recursive
before_build:
  - cd "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC"
  - call dir /s dumpbin.exe
  - cd %APPVEYOR_BUILD_FOLDER%
build_script: appveyor.py
