image: Visual Studio 2019
install: git submodule update --init --recursive
for:
  -
    matrix:
      only:
        -
          platform: x86
    build_script:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall32.bat"
      - appveyor.py
  -
    matrix:
      only:
        -
          platform: x64
    build_script:
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall64.bat"
      - appveyor.py