image: Visual Studio 2019
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
install:
  git submodule update --init --recursive
build:
  project: gcheapstat.sln
for:
  -
    matrix:
      only:
        - platform: x86
      only:
        - configuration: Release
    after_build:
    - cmd: 7z a gcheapstat32.zip %APPVEYOR_BUILD_FOLDER%\out\x86\Release\gcheapstat.exe
    - cmd: 7z a gcheapstat32.zip %APPVEYOR_BUILD_FOLDER%\out\x86\Release\gcheapstat.pdb
    - cmd: 7z a gcheapstat32.zip %APPVEYOR_BUILD_FOLDER%\out\x86\Release\gcheapstatsvc.pdb
    artifacts:
    - path: gcheapstat32.zip
  -
    matrix:
      only:
        - platform: x64
      only:
        - configuration: Release
    after_build:
    - cmd: 7z a gcheapstat64.zip %APPVEYOR_BUILD_FOLDER%\out\x64\Release\gcheapstat.exe
    - cmd: 7z a gcheapstat64.zip %APPVEYOR_BUILD_FOLDER%\out\x64\Release\gcheapstat.pdb
    - cmd: 7z a gcheapstat64.zip %APPVEYOR_BUILD_FOLDER%\out\x64\Release\gcheapstatsvc.pdb
    artifacts:
    - path: gcheapstat64.zip
